In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

### 电影题材关联
- 数据集：MovieLens(small)(http://files.grouplens.org/datasets/movielens/ml-latest-small.zip)

In [2]:
movies = pd.read_csv('../data/ml-latest-small/movies.csv')

In [3]:
movies.head(10)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

#### 1、将数据集转换为one-hot格式

In [5]:
genres = movies.genres.str.get_dummies()

In [6]:
movies_solved = movies.drop('genres', 1).join(genres)

In [7]:
movies_solved.head(10)

,movieId,title,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,6,Heat (1995),0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
6,7,Sabrina (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
7,8,Tom and Huck (1995),0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,Sudden Death (1995),0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,GoldenEye (1995),0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [8]:
movies_solved.shape

(9742, 22)

#### 2、重新设置索引

In [9]:
movies_solved.set_index(['movieId', 'title'], inplace=True)

In [10]:
movies_solved.head()

,,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,title,,,,,,,,,,,,,,,,,,,,
1,Toy Story (1995),0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,Jumanji (1995),0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,Grumpier Old Men (1995),0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,Waiting to Exhale (1995),0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
5,Father of the Bride Part II (1995),0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

#### 3、获取频繁项集

In [11]:
frequent_itemsets = apriori(movies_solved, use_colnames=True, min_support=0.025)

##### apriori
- use_colnames: bool, True-使用列名, False: 不使用列名表示项集，默认是用索引表示
- min_support: 最小支持度，在数据量较大需慎重选择，否则会导致筛选出的频繁项集为空

In [12]:
frequent_itemsets

     support                  itemsets
0   0.187641                  (Action)
1   0.129645               (Adventure)
2   0.062718               (Animation)
3   0.068158                (Children)
4   0.385547                  (Comedy)
5   0.123075                   (Crime)
6   0.045165             (Documentary)
7   0.447649                   (Drama)
8   0.079963                 (Fantasy)
9   0.100390                  (Horror)
10  0.034285                 (Musical)
11  0.058817                 (Mystery)
12  0.163827                 (Romance)
13  0.100595                  (Sci-Fi)
14  0.194416                (Thriller)
15  0.039212                     (War)
16  0.062615       (Adventure, Action)
17  0.044036          (Comedy, Action)
18  0.042907           (Crime, Action)
19  0.054301           (Drama, Action)
20  0.046294          (Action, Sci-Fi)
21  0.067235        (Thriller, Action)
22  0.025354    (Animation, Adventure)
23  0.032026     (Adventure, Children)
24  0.040957       (Comedy, Adventure)
25  0.031924        (Drama, Adventure)
26  0.034285      (Fantasy, Adventure)
27  0.031410       (Adventure, Sci-Fi)
28  0.031000     (Animation, Children)
29  0.027612       (Comedy, Animation)
30  0.037159        (Comedy, Children)
31  0.035414           (Comedy, Crime)
32  0.103983           (Comedy, Drama)
33  0.030076         (Fantasy, Comedy)
34  0.090741         (Romance, Comedy)
35  0.065387            (Drama, Crime)
36  0.058407         (Thriller, Crime)
37  0.029563          (Drama, Mystery)
38  0.095874          (Romance, Drama)
39  0.085403         (Drama, Thriller)
40  0.030589              (War, Drama)
41  0.047116        (Thriller, Horror)
42  0.036338       (Thriller, Mystery)
43  0.031000        (Thriller, Sci-Fi)
44  0.035106  (Romance, Comedy, Drama)
45  0.031718  (Drama, Crime, Thriller)

#### 3、计算关联规则
- metric: 一般可指定lift(提升度), confidence(置信度), support(支持度)
- min_threshold: 最小阈值，根据数据量需谨慎选择

In [13]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1.25)

In [14]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Adventure),(Action),0.129645,0.187641,0.062615,0.482977,2.573940,0.038289,1.571224
1,(Action),(Adventure),0.187641,0.129645,0.062615,0.333698,2.573940,0.038289,1.306247
2,(Crime),(Action),0.123075,0.187641,0.042907,0.348624,1.857929,0.019813,1.247142
3,(Action),(Crime),0.187641,0.123075,0.042907,0.228665,1.857929,0.019813,1.136892
4,(Action),(Sci-Fi),0.187641,0.100595,0.046294,0.246718,2.452576,0.027419,1.193981
5,(Sci-Fi),(Action),0.100595,0.187641,0.046294,0.460204,2.452576,0.027419,1.504937
6,(Thriller),(Action),0.194416,0.187641,0.067235,0.345829,1.843034,0.030754,1.241814
7,(Action),(Thriller),0.187641,0.194416,0.067235,0.358315,1.843034,0.030754,1.255420
8,(Animation),(Adventure),0.062718,0.129645,0.025354,0.404255,3.118175,0.017223,1.460953
9,(Adventure),(Animation),0.129645,0.062718,0.025354,0.195566,3.118175,0.017223,1.165145
10,(Adventure),(Children),0.129645,0.068158,0.032026,0.247031,3.624360,0.023190,1.237556
11,(Children),(Adventure),0.068158,0.129645,0.032026,0.469880,3.624360,0.023190,1.641806
12,(Fantasy),(Adventure),0.079963,0.129645,0.034285,0.428755,3.307149,0.023918,1.523610
13,(Adventure),(Fantasy),0.129645,0.079963,0.034285,0.264450,3.307149,0.023918,1.250815
14,(Adventure),(Sci-Fi),0.129645,0.100595,0.031410,0.242280,2.408464,0.018369,1.186989
15,(Sci-Fi),(Adventure),0.100595,0.129645,0.031410,0.312245,2.408464,0.018369,1.265502
16,(Animation),(Children),0.062718,0.068158,0.031000,0.494272,7.251799,0.026725,1.842573
17,(Children),(Animation),0.068158,0.062718,0.031000,0.454819,7.251799,0.026725,1.719213
18,(Comedy),(Children),0.385547,0.068158,0.037159,0.096379,1.414044,0.010880,1.031231
19,(Children),(Comedy),0.068158,0.385547,0.037159,0.545181,1.414044,0.010880,1.350983
20,(Romance),(Comedy),0.163827,0.385547,0.090741,0.553885,1.436620,0.027578,1.377341
21,(Comedy),(Romance),0.385547,0.163827,0.090741,0.235357,1.436620,0.027578,1.093547
22,(Thriller),(Crime),0.194416,0.123075,0.058407,0.300422,2.440963,0.034479,1.253506
23,(Crime),(Thriller),0.123075,0.194416,0.058407,0.474562,2.440963,0.034479,1.533167
24,(Romance),(Drama),0.163827,0.447649,0.095874,0.585213,1.307302,0.022537,1.331649
25,(Drama),(Romance),0.447649,0.163827,0.095874,0.214171,1.307302,0.022537,1.064065
26,(War),(Drama),0.039212,0.447649,0.030589,0.780105,1.742669,0.013036,2.511880
27,(Drama),(War),0.447649,0.039212,0.030589,0.068333,1.742669,0.013036,1.031257
28,(Thriller),(Horror),0.194416,0.100390,0.047116,0.242344,2.414026,0.027598,1.187360
29,(Horror),(Thriller),0.100390,0.194416,0.047116,0.469325,2.414026,0.027598,1.518037
30,(Thriller),(Mystery),0.194416,0.058817,0.036338,0.186906,3.177729,0.024902,1.157532
31,(Mystery),(Thriller),0.058817,0.194416,0.036338,0.617801,3.177729,0.024902,2.107761
32,(Thriller),(Sci-Fi),0.194416,0.100595,0.031000,0.159451,1.585072,0.011442,1.070020
33,(Sci-Fi),(Thriller),0.100595,0.194416,0.031000,0.308163,1.585072,0.011442,1.164414
34,"(Comedy, Drama)",(Romance),0.103983,0.163827,0.035106,0.337611,2.060781,0.018071,1.262360
35,(Romance),"(Comedy, Drama)",0.163827,0.103983,0.035106,0.214286,2.060781,0.018071,1.140386
36,"(Drama, Crime)",(Thriller),0.065387,0.194416,0.031718,0.485086,2.495096,0.019006,1.564503
37,"(Drama, Thriller)",(Crime),0.085403,0.123075,0.031718,0.371394,3.017617,0.021207,1.395031
38,(Crime),"(Drama, Thriller)",0.123075,0.085403,0.031718,0.257715,3.017617,0.021207,1.232136
39,(Thriller),"(Drama, Crime)",0.194416,0.065387,0.031718,0.163147,2.495096,0.019006,1.116818

#### 4、在根据其他条件筛选出合适的数据
- 如: 获取提升度大于5的关联规则

In [15]:
rules[rules.lift>5]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
16,(Animation),(Children),0.062718,0.068158,0.031,0.494272,7.251799,0.026725,1.842573
17,(Children),(Animation),0.068158,0.062718,0.031,0.454819,7.251799,0.026725,1.719213

##### Children(儿童题材)和Animation(动漫)这两题材是最相关的，根据常识也可分辨出来

#### 5、查看数据集中包含以上两题材的数据的信息

In [17]:
movies[(movies.genres.str.contains('Children'))&(movies.genres.str.contains('Animation'))]

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
12,13,Balto (1995),Adventure|Animation|Children
44,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
205,239,"Goofy Movie, A (1995)",Animation|Children|Comedy|Romance
272,313,"Swan Princess, The (1994)",Animation|Children
...,...,...,...
9629,178827,Paddington 2 (2017),Adventure|Animation|Children|Comedy
9657,180987,Ferdinand (2017),Animation|Children|Comedy
9664,182293,Hare-um Scare-um (1939),Animation|Children|Comedy
9666,182299,Porky's Hare Hunt (1938),Animation|Children|Comedy
9708,187541,Incredibles 2 (2018),Action|Adventure|Animation|Children